//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 12:57:42 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/demo/springsoapWebservice/loanEligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.demo.client.springsoapWebservice.loaneligibility;
